### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ardahan1423** [SoGoesLight/ValorantBot#1]
Hello, I followed it step by step and did it but it does not walk or squeeze as shown in the picture, it just stays in place
![Adsız](https://user-images.githubusercontent.com/52678045/103322241-6ce84d00-4a4e-11eb-8359-4492b1d08192.png)

**Comment by sogoeslight** [comment]
Problem appeared because of a low screen resolution.
Already discussed, so closing the issue.
