### ISSUE TITLE
Dont buy

### ISSUE THREAD

**Issue by bulyoked** [SoGoesLight/ValorantBot#2]
Bot working select dm and start match but in game dont buy anything pls help

**Comment by sogoeslight** [comment]
Could you please describe a problem bit more?
Bot does not buy anything and you are kicked off the match because of afk?
If you are not kicked, then its actually fine since you still get all the exp for the match

**Comment by bulyoked** [comment]
Bot does not buy anything and you are kicked off the match because of afk?  yes i 2-3 time get inactivity i used old versions didnt get any problem like this

**Comment by sogoeslight** [comment]
That's strange, I will try to fix it this week
